name: Harmonia Herbs
favicon: null
layout_spectrum: 0.05340437311679125
typography_spectrum: 0.7621033487375826
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6816479777917266
  lightness: 0.19013156578876078
  saturation: 0.1324901634361595
  rhythmicContrast: 0.6091325397137552
purpose: []
